#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
#runApplication topoSet
#runApplication createBaffles -overwrite

runApplication setFields

runApplication decomposePar
runApplication mpiexec -n 32 interFoam -parallel | tee log
runApplication reconstructPar
runApplication postProcess -func "grad(p_rgh)"
runApplication postProcess -func "grad(p)"
runApplication postProcess -func "grad(k)"
runApplication postProcess -func "grad(U)"
runApplication postProcess -func "grad(R)"



runApplication paraFoam
#------------------------------------------------------------------------------
