#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
cp -r 0.orig 0

runApplication blockMesh
# runApplication blockMesh
#runApplication topoSet
#runApplication createBaffles -overwrite

# runApplication setFields
runApplication pimpleFoam

# runApplication decomposePar
# runApplication mpiexec -n 8 pimpleFoam -parallel
# runApplication reconstructPar




# runApplication paraFoam

#------------------------------------------------------------------------------
